import type { Metadata } from "next";
import "@/assets/style/globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body className='h-[100dvh] w-[100dvw]'>
        {children}
      </body>
    </html>
  );
}
